FROM quay.io/keycloak/keycloak:19.0.2

USER root
# ENV TZ=UTC+2
# ENV TZ=CEST
ENV TZ=Europe/Oslo

# set timezone for container (not kc)
# set timezone (TZ not considered in ubi8-minimal image)
RUN microdnf update && microdnf reinstall tzdata && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && microdnf clean all

# set timezone for kc
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
